### ISSUE TITLE
problem while using python script

### ISSUE THREAD

**Issue by flyboyhoward** [swatbotics/apriltag#11]
hi, I facing up with **Segmentation fault (core dumped)** while I am trying to run python script. I choose an image from hallway folder for detection in my code.

these are my codes below(modified from https://pypi.org/project/apriltag/):

import apriltag
import cv2

img = cv2.imread('/home/wwh/my_apriltag/apriltag/images/hallway/IMG_0612.jpg',cv2.IMREAD_GRAYSCALE)
detector = apriltag.Detector()
result = detector.detect(img)
print result

**Comment by mzucker** [comment]
I am not the maintainer of the pypi package, please contact them for support; or, you can try to replicate this issue using the latest commit from this repository. 

If you are still having problems with a current checkout from this repository, please open a new issue that specifies what OS, architecture, & compiler you are using so I can try to investigate.
