### ISSUE TITLE
I got a Error in python3.5

### ISSUE THREAD

**Issue by niteofhunter** [swatbotics/apriltag#13]
in python. I type 

import apriltag
detector = apriltag.Detector()

but when I type it, I got a Error message

selfdir is /usr/local/lib/python3.5/dist-packages
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/apriltag.py", line 272, in __init__
    self.libc = ctypes.CDLL(filename)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libapriltag.so: cannot open shared object file: No such file or directory

how can I fix that?

**Comment by mzucker** [comment]
Did you build the software before trying to run the Python scripts? I just updated the [README.md](/README.md) file to clarify that this needs to happen.

**Comment by niteofhunter** [comment]
Oh it works now!!! Thanks!!!

by the way is this library have any tutorial or guide? (I'm a novice of coding T,T)

**Comment by mzucker** [comment]
No tutorial or guide, sorry. Glad it works now.
