### ISSUE TITLE
Unable to detect tag with border=2

### ISSUE THREAD

**Issue by XiaoxingChen** [swatbotics/apriltag#21]
Hi there,  

I use your python module to detect marker, it works fine on tag with border=1. However, when I use the calibration [pattern](https://drive.google.com/file/d/0B0T1sizOvRsUdjFJem9mQXdiMTQ/edit) from ETHZ Kalibr(a calibration tool) [here](https://github.com/ethz-asl/kalibr/wiki/downloads), whose  pattern border is 2, the python module detected nothing.   

   I've checked the pattern parameters, like family tag36h11, start with ID=30. Could you please kindly give me some suggestions?

Here is my code:
```
import apriltag
import cv2

if __name__ == "__main__":
    from sys import argv
    if len(argv) < 2:
        print("example: python tag_recognition.py path/to/img.png")
        quit()

    img_filename = argv[1]
    img = cv2.imread(img_filename, cv2.IMREAD_GRAYSCALE)
    options = apriltag.DetectorOptions(families='tag36h11',  
                                border=2,
                                nthreads=4,
                                quad_decimate=1.0,
                                quad_blur=0.0,
                                refine_edges=True,
                                refine_decode=False,
                                refine_pose=False,
                                debug=True,
                                quad_contours=True)
    detector = apriltag.Detector(options = options)
    result = detector.detect(img)
    print(result)
```

Many thanks!
![kalibr_tags](https://user-images.githubusercontent.com/16934019/67745877-4270bd80-fa60-11e9-9967-f219fe5bd0a1.png)

**Comment by mzucker** [comment]
I'm wondering if the corner squares in between the tags are interfering. What if that space was white instead of black?

**Comment by nikostsagk** [comment]
try `families=tag16h5`

**Comment by Yzhbuaa** [comment]
hello, how do you fix this issue?

**Comment by KarolineH** [comment]
Same problem here, even after removing the black corner squares. 
Setting the option border=2 (or higher) does not seem to change anything, the detector only ever detects markers with a single-width black border.
