### ISSUE TITLE
Extracting pose data to other python scripts

### ISSUE THREAD

**Issue by KshitijKarnawat** [swatbotics/apriltag#26]
Hi @mzucker,

When I run your wrapper the code to print the pose matrix is inside the wrapper. Is there anyway that I can access the pose variable in other python scripts like demo.py 

I want to plot the values that I am getting from the pose (x,y and z) to estimate the amount of error I am getting after calibrating the camera so that I can further develop a filter of some sort to rectify this error

**Comment by lpmsh** [comment]
@KshitijKarnawat 
You should be able to just import the apriltag.py file and call the function. I used that and just passed it the parameters it needed from my calibrations. You should be able to manipulate that data from there. I had to make some modifications to the package to get what I wanted from it so you may have to do some tinkering for your specific needs.

If you can't get the module imported, the `apriltag` package on pypi is almost exactly the same and you can just install it through pip and import it as you would any other package. https://pypi.org/project/apriltags/

It is pretty old and not maintained. I could only get it to work with Python 3.7.1

Let me know if I can help further.
