### ISSUE TITLE
Error with libapriltag.so on Ubuntu 16

### ISSUE THREAD

**Issue by Sukhoi-T50** [swatbotics/apriltag#9]
Hello,

Installed Aprtiltag according to the site and the demo worked fine but when I tried to run the script from https://pypi.org/project/apriltags/ , I get the following error: 

Traceback (most recent call last):
  File "ATtest.py", line 8, in <module>
    detector = Detector()
  File "/home/odroid/apriltag-0.0.13/python/apriltag.py", line 272, in __init__
    self.libc = ctypes.CDLL(filename)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libapriltag.so: cannot open shared object file: No such file or directory
Exception AttributeError: "'Detector' object has no attribute 'libc'" in <bound method Detector.__del__ of <apriltag.Detector object at 0xafd184d0>> ignored

any idea on how to fix the above error?

Thanks

**Comment by mzucker** [comment]
Right now the Python side of things assumes that it is being run from the build directory of the project, which is dumb and should be fixed. I'll try to push out a fix later today.

**Comment by mzucker** [comment]
Ok, d440a91 introduces the ability to optionally specify a list of paths to the Detector class initializer. You can use this mechanism, or you can make sure the .so file is installed to the system library directory using "make install" before running your own python code. Hope that helps!

**Comment by Sukhoi-T50** [comment]
Sorry for the late reply. It is working now. Thanks.

**Comment by mzucker** [comment]
Thanks for following up.

**Comment by yuan0623** [comment]
mzucker , Hi, I had the same error, can you tell me more about the 'make install' ? I'm not the expert on Ubuntu I might need additional help. Thanks in advance!
